spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**

test:
    value : "oussama"